version: "3.8"
services:
  app1:
    container_name: chamomile
    build:
      context: .
      dockerfile: dockerfile
      args:
        VITE_FRONTEND_BUILD: ${VITE_FRONTEND_BUILD}
        VITE_BACKEND_BUILD: ${VITE_BACKEND_BUILD} 
        VITE_BUILD_TIMESTAMP: ${VITE_BUILD_TIMESTAMP}
    ports:
      - "7880:7880"
    environment:
      - DB_URL=Host=host.docker.internal:5432;Database=(db);Username=(username);Password=(password);
      - SD_URL=http://host.docker.internal:7860
      - VITE_FRONTEND_BUILD=${VITE_FRONTEND_BUILD}
      - VITE_BACKEND_BUILD=${VITE_BACKEND_BUILD}