CREATE TABLE chamomile.images (
	image_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	image_prompt_tx text NULL,
	image_neg_prompt_tx text NULL,
	image_step_cnt int4 NULL,
	image_sampler_tx text NULL,
	image_schedule_tp text NULL,
	image_cfg_scl_num float8 NULL,
	image_seed_num int8 NULL,
	image_hght_num int4 NULL,
	image_wdth_num int4 NULL,
	image_fav_in bool DEFAULT false NULL,
	image_bytes_tx bytea NOT NULL,
	cre_ts timestamp(4) DEFAULT now() NULL,
	image_hires_bytes_tx bytea NULL,
	image_hires_in bool GENERATED ALWAYS AS (image_hires_bytes_tx IS NOT NULL AND length(image_hires_bytes_tx) > 0) STORED NULL,
	image_base_prompt_tx text NULL,
	image_base_prompt_fts tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, image_base_prompt_tx)) STORED NULL,
	image_prompt_fts tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, image_prompt_tx)) STORED NULL,
	CONSTRAINT pk_image PRIMARY KEY (image_id)
	--CONSTRAINT images_models_fk FOREIGN KEY (model_title_tx) REFERENCES chamomile.models(model_title_tx)
);

CREATE TABLE chamomile.models (
	model_title_tx text not null,
	model_nm text not null,
	model_desc_tx text not null,
	model_avail_in boolean not null,
	model_type_tx varchar null, 
	model_type_cd varchar null,
	image_id int4 null,
	CONSTRAINT pk_model PRIMARY KEY (model_title_tx),
	CONSTRAINT fk_model_image FOREIGN KEY (image_id) REFERENCES chamomile.images(image_id)
);


CREATE TABLE chamomile.lora (
	lora_alias_tx         text,
	lora_nm               text,
	lora_desc_tx          text,
	lora_sample_prompt_tx text,
	lora_avail_in        boolean not null,
	lora_type_cd          varchar,
	image_id int4 null,
	CONSTRAINT pk_lora PRIMARY KEY (lora_alias_tx),
	CONSTRAINT fk_lora_image FOREIGN KEY (image_id) REFERENCES chamomile.images(image_id)
);


CREATE TABLE chamomile.prompts (
	prompt_id             int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	prompt_nm             text,
	prompt_prompt_tx      text,
	prompt_neg_prompt_tx  text,
	prompt_step_cnt       int4,
	prompt_sampler_tx     text,
	prompt_schedule_tp    text,
	prompt_cfg_scl_num    int4,
	prompt_hght_num       int4,
	prompt_wdth_num       int4,
	image_id int4 null,
	CONSTRAINT pk_prompt PRIMARY KEY (prompt_id),
	CONSTRAINT fk_prompt_image FOREIGN KEY (image_id) REFERENCES chamomile.images(image_id)
);

ALTER TABLE chamomile.images ADD model_title_tx text NULL;
ALTER TABLE chamomile.images ADD CONSTRAINT images_models_fk FOREIGN KEY (model_title_tx) REFERENCES chamomile.models(model_title_tx);

CREATE TABLE chamomile.images_lora_map (
	image_id int4 NULL,
	lora_alias_tx text NULL,
	CONSTRAINT images_lora_map_images_fk FOREIGN KEY (image_id) REFERENCES chamomile.images(image_id),
	CONSTRAINT images_lora_map_lora_fk FOREIGN KEY (lora_alias_tx) REFERENCES chamomile.lora(lora_alias_tx)
);


CREATE INDEX idx_image_base_prompt_fts
  ON chamomile.images USING GIN (image_base_prompt_fts);

CREATE INDEX idx_image_prompt_fts
  ON chamomile.images USING GIN (image_prompt_fts);


  CREATE TABLE chamomile.albums (
	album_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	album_nm text NULL,
	album_thumb_id int4 NULL,
	album_query_tx text NULL,
	
	CONSTRAINT pk_album PRIMARY KEY (album_id),
	CONSTRAINT album_thumbnail_fk FOREIGN KEY (album_thumb_id) REFERENCES chamomile.images(image_id)
);

  CREATE TABLE chamomile.album_map (
	image_id int4 NOT NULL,
	album_id int4 NOT NULL,
	CONSTRAINT albummap_image_fk FOREIGN KEY (image_id) REFERENCES chamomile.images(image_id) on delete cascade ,
	CONSTRAINT albummap_album_fk FOREIGN KEY (album_id) REFERENCES chamomile.albums(album_id) on delete cascade
);


ALTER TABLE chamomile.images ADD image_gen_ms_nb int4 NULL;

ALTER table chamomile.images add image_notes_tx text DEFAULT '';

alter table images add image_notes_fts tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, image_notes_tx)) STORED null;

alter table images add image_download_ct int4 default 0;

ALTER TABLE images
ADD COLUMN image_effective_size_nb integer
GENERATED ALWAYS AS (
  CASE
    WHEN image_hires_bytes_tx IS NOT NULL THEN length(image_hires_bytes_tx)
    ELSE length(image_bytes_tx)
  END
) STORED;


CREATE OR REPLACE FUNCTION extract_keywords(
  image_id INT,
  image_prompt_tx TEXT,
  cre_ts timestamp
)
RETURNS TABLE (
  keyword TEXT,
  image_id INT,
  cre_ts timestamp
) AS $$
  SELECT
    TRIM(k) AS keyword,
    image_id, cre_ts
  FROM unnest(
   	regexp_split_to_array(
  TRIM(
    REGEXP_REPLACE(
      REGEXP_REPLACE(
        REGEXP_REPLACE(image_prompt_tx, '[()]', ' ', 'g'),       -- Remove parentheses
        '<lora:[^>]+>',                                     -- Remove LoRA tags
        ' ',
        'gi'
      ),
      E'[\\n\\r\\t]+', ' ', 'g'                            -- Normalize linebreaks/tabs to spaces
    )
  ),
  E'[,\n\r]| {2,}'                                        -- Split on commas, linebreaks, or 2+ spaces
)
   -- split by comma or linebreaks
  ) AS k
  WHERE TRIM(k) <> '';
$$ LANGUAGE sql STABLE;

ALTER TABLE chamomile.albums ADD album_hidden_in boolean DEFAULT false NULL;
ALTER TABLE chamomile.images add image_hidden_in bool DEFAULT false NULL;
ALTER TABLE chamomile.images add img_addtl_info_mv jsonb null;

-- chamomile.album_meta source

CREATE OR REPLACE VIEW chamomile.album_meta
AS WITH first_four AS (
         SELECT ranked.album_id,
            ranked.image_id
           FROM ( SELECT album_map.album_id,
                    album_map.image_id,
                    row_number() OVER (PARTITION BY album_map.album_id ORDER BY album_map.image_id) AS rn
                   FROM album_map) ranked
          WHERE ranked.rn <= 4
        )
 SELECT a.album_id,
    a.album_nm,
    count(am.image_id) AS album_image_ct,
    a.album_thumb_id,
    ff.album_sample_ids,
    min(img.cre_ts) AS min_ts,
    max(img.cre_ts) AS max_ts,
    a.album_query_tx,
    a.album_hidden_in
   FROM albums a
     LEFT JOIN album_map am ON a.album_id = am.album_id
     LEFT JOIN images img ON am.image_id = img.image_id
     LEFT JOIN ( SELECT first_four.album_id,
            array_agg(first_four.image_id ORDER BY first_four.image_id) AS album_sample_ids
           FROM first_four
          GROUP BY first_four.album_id) ff ON a.album_id = ff.album_id
  GROUP BY a.album_id, a.album_nm, a.album_thumb_id, ff.album_sample_ids, a.album_query_tx;



CREATE TABLE grids (
    grid_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	grid_nm text not null,
    grid_prompt_tx TEXT NOT NULL,
    grid_notes_tx TEXT,
	grid_negative_prompt_tx TEXT NOT NULL,
    grid_step_cnt int4 NOT NULL,
    grid_sampler_tx TEXT NOT NULL,
    grid_schedule_tp TEXT NOT NULL,
    grid_cfg_scl_num float8 NOT NULL,
    grid_seed_num int8 NOT NULL,
    grid_hght_num int4 NOT NULL,
    grid_wdth_num int4 NOT NULL,
    grid_generation_duration_ms INTEGER,
	grid_xval_cd TEXT NOT NULL,
    grid_xval TEXT[] NOT NULL,
    grid_yval_cd TEXT NOT NULL,
    grid_yval TEXT[] NOT NULL,
    cre_ts TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_grid PRIMARY KEY (grid_id)
);



CREATE OR REPLACE FUNCTION hash_prompt(input_text text)
RETURNS text AS $$
DECLARE
    normalized text;
BEGIN
    -- normalize: lowercase, trim, collapse all whitespace (space, tabs, newlines) to single space
    normalized := regexp_replace(lower(trim(input_text)), '\s+', ' ', 'g');
    RETURN md5(normalized);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

ALTER TABLE images
ADD COLUMN image_prompts_hash text GENERATED ALWAYS AS (
    hash_prompt(image_prompt_tx) || hash_prompt(image_neg_prompt_tx)
) STORED;

CREATE INDEX idx_images_prompts_hash ON images(image_prompts_hash);

ALTER TABLE images
ADD COLUMN image_base_prompt_hash text GENERATED ALWAYS AS (
    hash_prompt(image_base_prompt_tx)
) STORED;

CREATE INDEX idx_images_base_prompts_hash ON images(image_base_prompt_hash);

alter table models add column model_tag_tx varchar(50) default '';
alter table lora add column lora_tag_tx varchar(50) default '';

create table templates (
	templ_nm text not null,
	templ_desc_tx text, 
	templ_params_mv JSONB,
	templ_tx text,
	image_id int4,
	CONSTRAINT pk_templates PRIMARY KEY (templ_nm)
)

--I messed up the initial set up for this for some reason

ALTER TABLE chamomile.models
ALTER COLUMN model_tag_tx
SET DEFAULT ARRAY[]::varchar(50)[];

ALTER TABLE chamomile.models
ALTER COLUMN model_tag_tx
TYPE varchar(50)[]
USING 
    CASE
        WHEN model_tag_tx IS NULL OR model_tag_tx = '' THEN ARRAY[]::varchar(50)[]
        ELSE ARRAY[model_tag_tx]::varchar(50)[]
    END;


ALTER TABLE chamomile.lora
ALTER COLUMN lora_tag_tx
SET DEFAULT ARRAY[]::varchar(50)[];

ALTER TABLE chamomile.lora
ALTER COLUMN lora_tag_tx
TYPE varchar(50)[]
USING 
    CASE
        WHEN lora_tag_tx IS NULL OR lora_tag_tx = '' THEN ARRAY[]::varchar(50)[]
        ELSE ARRAY[lora_tag_tx]::varchar(50)[]
    END;