CREATE TABLE chamomile.images (
	image_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	image_prompt_tx text NULL,
	image_neg_prompt_tx text NULL,
	image_step_cnt int4 NULL,
	image_sampler_tx text NULL,
	image_schedule_tp text NULL,
	image_cfg_scl_num float8 NULL,
	image_seed_num int8 NULL,
	image_hght_num int4 NULL,
	image_wdth_num int4 NULL,
	image_fav_in bool DEFAULT false NULL,
	image_bytes_tx bytea NOT NULL,
	model_title_tx text NULL,
	cre_ts timestamp(4) DEFAULT now() NULL,
	image_hires_bytes_tx bytea NULL,
	image_hires_in bool GENERATED ALWAYS AS (image_hires_bytes_tx IS NOT NULL AND length(image_hires_bytes_tx) > 0) STORED NULL,
	image_base_prompt_tx text NULL,

	-- I don't think anyone prompts in other languages but if so change the tsvector
	image_base_prompt_fts tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, image_base_prompt_tx)) STORED NULL,
	image_prompt_fts tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, image_prompt_tx)) STORED NULL,

	CONSTRAINT pk_image PRIMARY KEY (image_id),
	CONSTRAINT images_models_fk FOREIGN KEY (model_title_tx) REFERENCES chamomile.models(model_title_tx)
);

CREATE TABLE chamomile.models (
	model_title_tx text not null,
	model_nm text not null,
	model_desc_tx text not null,
	model_avail_in boolean not null,
	model_type_tx varchar null, 
	model_type_cd varchar null,
	image_id int4 null,
	CONSTRAINT pk_model PRIMARY KEY (model_title_tx),
	CONSTRAINT fk_model_image FOREIGN KEY (image_id) REFERENCES chamomile.images(image_id)
);


CREATE TABLE chamomile.lora (
	lora_alias_tx         text,
	lora_nm               text,
	lora_desc_tx          text,
	lora_sample_prompt_tx text,
	lora_avail_in        boolean not null,
	lora_type_cd          varchar,
	image_id int4 null,
	CONSTRAINT pk_lora PRIMARY KEY (lora_alias_tx),
	CONSTRAINT fk_lora_image FOREIGN KEY (image_id) REFERENCES chamomile.images(image_id)
);


CREATE TABLE chamomile.prompts (
	prompt_id             int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	prompt_nm             text,
	prompt_prompt_tx      text,
	prompt_neg_prompt_tx  text,
	prompt_step_cnt       int4,
	prompt_sampler_tx     text,
	prompt_schedule_tp    text,
	prompt_cfg_scl_num    int4,
	prompt_hght_num       int4,
	prompt_wdth_num       int4,
	image_id int4 null,
	CONSTRAINT pk_prompt PRIMARY KEY (prompt_id),
	CONSTRAINT fk_prompt_image FOREIGN KEY (image_id) REFERENCES chamomile.images(image_id)
);

ALTER TABLE chamomile.images ADD model_title_tx text NULL;
ALTER TABLE chamomile.images ADD CONSTRAINT images_models_fk FOREIGN KEY (model_title_tx) REFERENCES chamomile.models(model_title_tx);

CREATE TABLE chamomile.images_lora_map (
	image_id int4 NULL,
	lora_alias_tx text NULL,
	CONSTRAINT images_lora_map_images_fk FOREIGN KEY (image_id) REFERENCES chamomile.images(image_id),
	CONSTRAINT images_lora_map_lora_fk FOREIGN KEY (lora_alias_tx) REFERENCES chamomile.lora(lora_alias_tx)
);


CREATE INDEX idx_image_base_prompt_fts
  ON chamomile.images USING GIN (image_base_prompt_fts);

CREATE INDEX idx_image_prompt_fts
  ON chamomile.images USING GIN (image_prompt_fts);


  CREATE TABLE chamomile.albums (
	album_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	album_nm text NULL,
	album_thumb_id int4 NULL,
	album_query_tx text NULL,
	
	CONSTRAINT pk_album PRIMARY KEY (album_id),
	CONSTRAINT album_thumbnail_fk FOREIGN KEY (album_thumb_id) REFERENCES chamomile.images(image_id)
);

  CREATE TABLE chamomile.album_map (
	image_id int4 NOT NULL,
	album_id int4 NOT NULL,
	CONSTRAINT albummap_image_fk FOREIGN KEY (image_id) REFERENCES chamomile.images(image_id) on delete cascade ,
	CONSTRAINT albummap_album_fk FOREIGN KEY (album_id) REFERENCES chamomile.albums(album_id) on delete cascade
);

CREATE OR REPLACE VIEW chamomile.album_meta as 
WITH first_four AS (
    SELECT
        album_id,
        image_id
    FROM (
        SELECT
            album_id,
            image_id,
            ROW_NUMBER() OVER (PARTITION BY album_id ORDER BY image_id) AS rn
        FROM chamomile.album_map
    ) ranked
    WHERE rn <= 4
)
SELECT
    a.album_id,
    a.album_nm,
    COUNT(am.image_id) AS album_image_ct,
    a.album_thumb_id,
    ff.album_sample_ids,
    MIN(img.cre_ts) AS min_ts,
    MAX(img.cre_ts) AS max_ts
	a.album_query_tx
FROM chamomile.albums a
LEFT JOIN chamomile.album_map am ON a.album_id = am.album_id
LEFT JOIN chamomile.images img ON am.image_id = img.image_id
LEFT JOIN (
    SELECT album_id, ARRAY_AGG(image_id ORDER BY image_id) AS album_sample_ids
    FROM first_four
    GROUP BY album_id
) ff ON a.album_id = ff.album_id
GROUP BY a.album_id, a.album_nm, a.album_thumb_id, ff.album_sample_ids, a.album_query_tx;

ALTER TABLE chamomile.images ADD image_gen_ms_nb int4 NULL;
alter table images add image_notes_tx DEFAULT '';

alter table images add image_notes_fts tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, image_notes_tx)) STORED null;

alter table images add image_download_ct int4 default 0;