CREATE TABLE chamomille.images (
	image_id            int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_prompt_tx     text,
	image_base_prompt_tx text,
    image_neg_prompt_tx text,
    image_step_cnt      int4,
    image_sampler_tx    text,
    image_schedule_tp   text,
    image_cfg_scl_num   float8,
    image_seed_num      int8,
    image_hght_num      int4,
    image_wdth_num      int4,
    image_fav_in        boolean default false,
    image_bytes_tx      bytea not null,
    cre_ts              timestamp(4),
	CONSTRAINT pk_image PRIMARY KEY (image_id)
);

CREATE TABLE chamomille.models (
	model_title_tx text not null,
	model_nm text not null,
	model_desc_tx text not null,
	model_avail_in boolean not null,
	image_id int4 null,
	CONSTRAINT pk_model PRIMARY KEY (model_title_tx),
	CONSTRAINT fk_model_image FOREIGN KEY (image_id) REFERENCES chamomille.images(image_id)
);


CREATE TABLE chamomille.lora (
	lora_alias_tx         text,
	lora_nm               text,
	lora_desc_tx          text,
	lora_sample_prompt_tx text,
	model_avail_in        boolean not null,
	image_id int4 null,
	CONSTRAINT pk_lora PRIMARY KEY (lora_alias_tx),
	CONSTRAINT fk_lora_image FOREIGN KEY (image_id) REFERENCES chamomille.images(image_id)
);


CREATE TABLE chamomille.prompts (
	prompt_id             int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	prompt_nm             text,
	prompt_prompt_tx      text,
	prompt_neg_prompt_tx  text,
	prompt_step_cnt       int4,
	prompt_sampler_tx     text,
	prompt_schedule_tp    text,
	prompt_cfg_scl_num    int4,
	prompt_hght_num       int4,
	prompt_wdth_num       int4,
	image_id int4 null,
	CONSTRAINT pk_prompt PRIMARY KEY (prompt_id),
	CONSTRAINT fk_prompt_image FOREIGN KEY (image_id) REFERENCES chamomille.images(image_id)
);

ALTER TABLE chamomille.images ADD model_title_tx text NULL;
ALTER TABLE chamomille.images ADD CONSTRAINT images_models_fk FOREIGN KEY (model_title_tx) REFERENCES chamomille.models(model_title_tx);

CREATE TABLE chamomille.images_lora_map (
	image_id int4 NULL,
	lora_alias_tx text NULL,
	CONSTRAINT images_lora_map_images_fk FOREIGN KEY (image_id) REFERENCES chamomille.images(image_id),
	CONSTRAINT images_lora_map_lora_fk FOREIGN KEY (lora_alias_tx) REFERENCES chamomille.lora(lora_alias_tx)
);



